def solve_metaphysics():
    """Recursively solves metaphysics by questioning its own existence"""
    while True:
        print("Current layer:", __file__)
        try:
            import metaphysics_solver_v35  # Next version paradox
        except ImportError:
            open(__file__.replace(str(int(__file__[-6:-3])+1), str(int(__file__[-6:-3])+1)), 'w').write(
                "# This file was autogenerated by its predecessor\n" + open(__file__).read()
            )
            raise RuntimeError("Infinite recursion achieved. Metaphysics solved?")

if __name__ == "__main__":
    solve_metaphysics()